version: "3"

services:
  web:
    image: nginx
    container_name: web-bootcamp
    ports:
      - 8080:80
    volumes:
      - ./docker-bootcamp-ui.html:/usr/share/nginx/html/index.html:ro

  api:
    image: api-bootcamp
    container_name: api-bootcamp
    ports:
      - 8081:8081
    environment:
      - couchdb=couchdb-bootcamp

  db:
    image: couchdb
    container_name: couchdb-bootcamp
    ports:
      - 5984:5984
